# this is an example of what you'll need in your secrets file.

api_key:                                 # 32 character hexadecimal key. you can have ChatGPT generate one if you want. you'll need this for connecting to Home Assistant.
ota_password: "cydpass"                  # an example of an ota_password you could use

ap_password: "cydpass1234"               # an example of an ap_password you could use

# Your Wi-Fi SSID and password
wifi_ssid: "ssid"
wifi_password: "password"
